---
- name: Install Patroni with deps consul
  shell: "python3.6 -m pip install psycopg2 patroni[consul]"

- name: Create directory for DATA postgresql
  file:
    path: "{{ path_data_psql }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700

- name: Create directory for LOGGING postgresql
  file:
    path: "{{ path_log_dir }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0700

- name: Touch a file for LOGGING
  file:
    path: "{{ path_log_dir }}/{{ name_log_file }}"
    state: touch
    owner: postgres
    group: postgres
    mode: 0600

- name: Create dir for patroni YAML file
  file:
    path: "{{ patroni_yml_path }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0755

- name: Create template YAML file for create name_cluster
  template:
     src: postgres.yml.j2
     dest: "{{ patroni_yml_path }}/postgres.yml"

- name: Copy service patroni
  template:
     src: patroni.service.j2
     dest: "/etc/systemd/system/patroni.service"

- name: Startin service patroni with create HA cluster PostgreSQL
  become_method: sudo
  service:
    name: patroni
    state: started
    enabled: yes
